import git from 'isomorphic-git';
import { obsidianHttpClient as http } from './httpClient';
import { ObsidianFS } from './fs';

export class GitManager {
    fs: ObsidianFS;
    dir: string;
    configDir: string;
    author: { name: string; email: string };

    constructor(fs: ObsidianFS, configDir: string) {
        this.fs = fs;
        this.configDir = configDir;
        this.dir = '/'; // Vault root
        this.author = { name: 'Obsidian User', email: 'user@example.com' };
    }

    async updateGitIgnore(userPaths: string) {
        let content = `# This file is auto-generated by Direct Git Sync. \n`;
        content += `# Please update custom ignore rules via the plugin settings.\n\n`;
        content += `# Core Obsidian ignores\n`;
        content += `${this.configDir}/workspace.json\n`;
        content += `${this.configDir}/workspace-mobile.json\n`;
        content += `${this.configDir}/workspace-cache/\n`;
        content += `.trash/\n`;
        content += `.obsidian/plugins/github-sync/data.json\n\n`;
        content += `# User defined ignore rules\n`;
        content += (userPaths || '').trim() + '\n';
        
        await this.fs.promises.writeFile('.gitignore', new TextEncoder().encode(content));
    }

    isIgnored(filepath: string): boolean {
        const lowerFilepath = filepath.toLowerCase();
        const ignoredPaths = [
            `${this.configDir}/workspace.json`.toLowerCase(),
            `${this.configDir}/workspace-mobile.json`.toLowerCase(),
            `${this.configDir}/workspace-cache/`.toLowerCase(),
            '.trash/'.toLowerCase(),
        ];

        return ignoredPaths.some(pattern =>
            pattern.endsWith('/')
                ? lowerFilepath.startsWith(pattern) || lowerFilepath === pattern.slice(0, -1)
                : lowerFilepath === pattern
        );
    }

    setAuthor(name: string, email: string) {
        if (name) this.author.name = name;
        if (email) this.author.email = email;
    }

    async isInitialized() {
        try {
            await git.log({ fs: this.fs, dir: this.dir, depth: 1 });
            return true;
        } catch {
            return false;
        }
    }

    async getStatusMatrix(): Promise<[string, number, number, number][]> {
        return await git.statusMatrix({ fs: this.fs, dir: this.dir });
    }

    async getHistory(limit = 20) {
        try {
            return await git.log({ fs: this.fs, dir: this.dir, depth: limit });
        } catch {
            return [];
        }
    }

    async getRemoteInfo(url: string, token: string) {
        return await git.getRemoteInfo({
            http,
            url,
            onAuth: () => ({ username: token })
        });
    }

    async initOrClone(url: string, token: string): Promise<string[]> {
        if (await this.isInitialized()) return [];
        
        await git.init({ fs: this.fs, dir: this.dir, defaultBranch: 'main' });
        await git.addRemote({ fs: this.fs, dir: this.dir, remote: 'origin', url });

        // If the remote already has history, fetch it and use it as our starting point.
        // This avoids "unrelated histories" issues when merging later.
        // Local-only files stay in the working directory and get staged by stageAll().
        try {
            const result = await git.fetch({
                fs: this.fs,
                http,
                dir: this.dir,
                url,
                remote: 'origin',
                onAuth: () => ({ username: token }),
                singleBranch: true
            });

            if (result.fetchHead) {
                // Determine the branch name from the remote
                let branch = 'main';
                if (result.defaultBranch) {
                    branch = result.defaultBranch.replace('refs/heads/', '');
                } else {
                    try {
                        // Infer branch if defaultBranch is null (older remotes)
                        const remoteInfo = await this.getRemoteInfo(url, token);
                        if (remoteInfo.refs?.heads) {
                            const matchingBranch = Object.keys(remoteInfo.refs.heads).find(
                                ref => remoteInfo.refs?.heads?.[ref] === result.fetchHead
                            );
                            if (matchingBranch) {
                                branch = matchingBranch;
                            } else if (remoteInfo.refs.heads['master']) {
                                branch = 'master';
                            }
                        }
                    } catch (e) {
                        console.debug('Failed to infer branch, defaulting to main', e);
                    }
                }

                // ── Collision check ──────────────────────────────────────────────
                // Before force-checkout overwrites disk files, back up any local
                // file that also exists in the remote tree (Dropbox-style).
                const today = new Date().toISOString().slice(0, 10);
                const localBackups: string[] = [];

                const remoteFiles = await git.listFiles({
                    fs: this.fs,
                    dir: this.dir,
                    ref: result.fetchHead
                });

                for (const filepath of remoteFiles) {
                    try {
                        await this.fs.promises.stat(filepath); // throws ENOENT if absent
                        // File exists locally — back it up before checkout overwrites it
                        const dotIndex = filepath.lastIndexOf('.');
                        const base = dotIndex !== -1 ? filepath.slice(0, dotIndex) : filepath;
                        const ext  = dotIndex !== -1 ? filepath.slice(dotIndex) : '';
                        const backupPath = `${base} (local backup - ${today})${ext}`;

                        const localContent = await this.fs.promises.readFile(filepath);
                        const contentToWrite = typeof localContent === 'string' 
                            ? new TextEncoder().encode(localContent) 
                            : localContent;
                        await this.fs.promises.writeFile(backupPath, contentToWrite);
                        localBackups.push(backupPath);
                    } catch {
                        // File doesn't exist locally — no collision, nothing to back up
                    }
                }
                // ────────────────────────────────────────────────────────────────

                // Point our local branch at the remote's latest commit
                await git.writeRef({
                    fs: this.fs,
                    dir: this.dir,
                    ref: `refs/heads/${branch}`,
                    value: result.fetchHead,
                    force: true
                });

                // Checkout to sync the index with HEAD.
                // force: true ensures remote files are written even if locals conflict.
                // Local-only files (not in remote) remain untouched in the working dir.
                await git.checkout({
                    fs: this.fs,
                    dir: this.dir,
                    ref: branch,
                    force: true
                });

                return localBackups;
            }
        } catch (e) {
            // Remote is empty or unreachable — that's fine.
            // The first push will create the remote history.
            console.debug('Initial fetch during setup skipped:', (e as Error).message);
        }

        return [];
    }


    async stageAll(): Promise<boolean> {
        const matrix = await git.statusMatrix({ fs: this.fs, dir: this.dir });
        let hasChanges = false;
        for (const row of matrix) {
            const filepath = row[0];
            const workdirStatus = row[2];
            const stageStatus = row[3];

            if (this.isIgnored(filepath)) continue;

            if (workdirStatus !== stageStatus) {
                if (workdirStatus === 0) {
                    await git.remove({ fs: this.fs, dir: this.dir, filepath });
                } else {
                    await git.add({ fs: this.fs, dir: this.dir, filepath });
                }
                hasChanges = true;
            }
        }
        return hasChanges;
    }

    async commit(message: string) {
        await git.commit({
            fs: this.fs,
            dir: this.dir,
            author: this.author,
            message
        });
    }

    async fetch(url: string, token: string) {
        const result = await git.fetch({
            fs: this.fs,
            http,
            dir: this.dir,
            url,
            remote: 'origin',
            onAuth: () => ({ username: token }),
            singleBranch: true
        });
        return result.fetchHead;
    }

    async merge(theirs: string | null): Promise<string[]> {
        if (!theirs) return []; // Remote had no commits or branches yet
        try {
            const branch = await git.currentBranch({ fs: this.fs, dir: this.dir, fullname: false }) || 'main';
            await git.merge({
                fs: this.fs,
                dir: this.dir,
                ours: branch,
                theirs: theirs,
                abortOnConflict: false,
                author: this.author
            });
            return []; // Clean merge — no conflicts
        } catch (e: unknown) {
            if (e instanceof Error && (e.name === 'MergeConflictError' || e.name === 'MergeNotSupportedError')) {
                // Dropbox-style resolution: save the remote version as a conflict copy,
                // keep the local version as the resolved content, and continue syncing.
                const filepaths: string[] = (e as { data?: { filepaths?: string[] } }).data?.filepaths ?? [];

                if (filepaths.length === 0) {
                    throw new Error('Merge conflict detected but could not identify conflicting files. Please sync using a Git client.');
                }

                const today = new Date().toISOString().slice(0, 10);
                const conflictCopies: string[] = [];

                for (const filepath of filepaths) {
                    try {
                        // Read the remote version of the file from the theirs commit
                        const { blob } = await git.readBlob({ fs: this.fs, dir: this.dir, oid: theirs, filepath });

                        // Build a conflict copy filename: "Notes (remote conflict - 2026-03-27).md"
                        const dotIndex = filepath.lastIndexOf('.');
                        const base = dotIndex !== -1 ? filepath.slice(0, dotIndex) : filepath;
                        const ext  = dotIndex !== -1 ? filepath.slice(dotIndex) : '';
                        const copyPath = `${base} (remote conflict - ${today})${ext}`;

                        // Write remote version as a new file in the vault
                        await this.fs.promises.writeFile(copyPath, blob);
                        conflictCopies.push(copyPath);

                        // Stage the conflict copy so it gets pushed too
                        await git.add({ fs: this.fs, dir: this.dir, filepath: copyPath });

                        // Stage the original file with the local (kept) content
                        await git.add({ fs: this.fs, dir: this.dir, filepath });
                    } catch (readErr) {
                        console.error(`[DirectGitSync] Failed to create conflict copy for "${filepath}":`, readErr);
                    }
                }

                return conflictCopies;
            }
            throw e;
        }
    }

    async push(url: string, token: string) {
        await git.push({
            fs: this.fs,
            http,
            dir: this.dir,
            remote: 'origin',
            onAuth: () => ({ username: token })
        });
    }
}
