import git from 'isomorphic-git';
import { obsidianHttpClient as http } from './httpClient';
import { ObsidianFS } from './fs';

export class GitManager {
    fs: ObsidianFS;
    dir: string;
    configDir: string;
    pluginId: string;
    ignoredPaths: string[];
    author: { name: string; email: string };

    constructor(fs: ObsidianFS, configDir: string, pluginId = 'direct-git-sync') {
        this.fs = fs;
        this.configDir = configDir;
        this.pluginId = pluginId;
        this.dir = '/';
        this.ignoredPaths = [];
        this.author = { name: 'Obsidian User', email: 'user@example.com' };
    }

    async updateGitIgnore(userPaths: string) {
        let content = `# This file is auto-generated by Direct Git Sync.\n`;
        content += `# Please update custom ignore rules via the plugin settings.\n\n`;
        content += `# Core Obsidian ignores\n`;
        content += `${this.configDir}/workspace.json\n`;
        content += `${this.configDir}/workspace-mobile.json\n`;
        content += `${this.configDir}/workspace-cache/\n`;
        content += `.trash/\n`;
        content += `${this.configDir}/plugins/${this.pluginId}/data.json\n\n`;
        content += `# User defined ignore rules\n`;
        content += (userPaths || '').trim() + '\n';

        this.ignoredPaths = [
            `${this.configDir}/workspace.json`,
            `${this.configDir}/workspace-mobile.json`,
            `${this.configDir}/workspace-cache/`,
            '.trash/',
            `${this.configDir}/plugins/${this.pluginId}/data.json`,
            ...(userPaths || '')
                .split('\n')
                .map(line => line.trim())
                .filter(line => line.length > 0 && !line.startsWith('#'))
        ].map(path => path.toLowerCase());

        await this.fs.promises.writeFile('.gitignore', new TextEncoder().encode(content));
    }

    isIgnored(filepath: string): boolean {
        const lowerFilepath = filepath.toLowerCase();
        return this.ignoredPaths.some(pattern =>
            pattern.endsWith('/')
                ? lowerFilepath.startsWith(pattern) || lowerFilepath === pattern.slice(0, -1)
                : lowerFilepath === pattern
        );
    }

    setAuthor(name: string, email: string) {
        if (name) this.author.name = name;
        if (email) this.author.email = email;
    }

    async isInitialized() {
        try {
            await git.log({ fs: this.fs, dir: this.dir, depth: 1 });
            return true;
        } catch {
            return false;
        }
    }

    async getStatusMatrix(): Promise<[string, number, number, number][]> {
        return await git.statusMatrix({ fs: this.fs, dir: this.dir });
    }

    async getHistory(limit = 20) {
        try {
            return await git.log({ fs: this.fs, dir: this.dir, depth: limit });
        } catch {
            return [];
        }
    }

    async getRemoteInfo(url: string, token: string) {
        return await git.getRemoteInfo({
            http,
            url,
            onAuth: () => ({ username: token })
        });
    }

    async initOrClone(url: string, token: string): Promise<string[]> {
        if (await this.isInitialized()) return [];

        await git.init({ fs: this.fs, dir: this.dir, defaultBranch: 'main' });
        await git.addRemote({ fs: this.fs, dir: this.dir, remote: 'origin', url });

        try {
            const result = await git.fetch({
                fs: this.fs,
                http,
                dir: this.dir,
                url,
                remote: 'origin',
                onAuth: () => ({ username: token }),
                singleBranch: true
            });

            if (result.fetchHead) {
                let branch = 'main';
                if (result.defaultBranch) {
                    branch = result.defaultBranch.replace('refs/heads/', '');
                } else {
                    try {
                        const remoteInfo = await this.getRemoteInfo(url, token);
                        const refsMap = remoteInfo.refs as Record<string, Record<string, string>> | undefined;
                        const heads = refsMap?.heads;
                        if (heads) {
                            const matchingBranch = Object.keys(heads).find(
                                ref => heads[ref] === result.fetchHead
                            );
                            if (matchingBranch) {
                                branch = matchingBranch;
                            } else if (heads['master']) {
                                branch = 'master';
                            }
                        }
                    } catch (e) {
                        console.debug('Failed to infer branch, defaulting to main', e);
                    }
                }

                const today = new Date().toISOString().slice(0, 10);
                const localBackups: string[] = [];

                const remoteFiles = await git.listFiles({
                    fs: this.fs,
                    dir: this.dir,
                    ref: result.fetchHead
                });

                for (const filepath of remoteFiles) {
                    try {
                        await this.fs.promises.stat(filepath);
                    } catch (error) {
                        if ((error as { code?: string }).code === 'ENOENT') {
                            continue;
                        }
                        throw error;
                    }

                    const dotIndex = filepath.lastIndexOf('.');
                    const base = dotIndex !== -1 ? filepath.slice(0, dotIndex) : filepath;
                    const ext = dotIndex !== -1 ? filepath.slice(dotIndex) : '';
                    const backupPath = `${base} (local backup - ${today})${ext}`;

                    const localContent = await this.fs.promises.readFile(filepath);
                    const contentToWrite = typeof localContent === 'string'
                        ? new TextEncoder().encode(localContent)
                        : localContent;
                    await this.fs.promises.writeFile(backupPath, contentToWrite);
                    localBackups.push(backupPath);
                }

                await git.writeRef({
                    fs: this.fs,
                    dir: this.dir,
                    ref: `refs/heads/${branch}`,
                    value: result.fetchHead,
                    force: true
                });

                await git.checkout({
                    fs: this.fs,
                    dir: this.dir,
                    ref: branch,
                    force: true
                });

                return localBackups;
            }
        } catch (e) {
            console.debug('Initial fetch during setup skipped:', (e as Error).message);
        }

        return [];
    }

    async stageAll(): Promise<boolean> {
        const matrix = await git.statusMatrix({ fs: this.fs, dir: this.dir });
        let hasChanges = false;
        for (const row of matrix) {
            const filepath = row[0];
            const workdirStatus = row[2];
            const stageStatus = row[3];

            if (this.isIgnored(filepath)) continue;

            if (workdirStatus !== stageStatus) {
                if (workdirStatus === 0) {
                    await git.remove({ fs: this.fs, dir: this.dir, filepath });
                } else {
                    await git.add({ fs: this.fs, dir: this.dir, filepath });
                }
                hasChanges = true;
            }
        }
        return hasChanges;
    }

    async commit(message: string) {
        await git.commit({
            fs: this.fs,
            dir: this.dir,
            author: this.author,
            message
        });
    }

    async fetch(url: string, token: string) {
        const result = await git.fetch({
            fs: this.fs,
            http,
            dir: this.dir,
            url,
            remote: 'origin',
            onAuth: () => ({ username: token }),
            singleBranch: true
        });
        return result.fetchHead;
    }

    async merge(theirs: string | null): Promise<string[]> {
        if (!theirs) return [];
        try {
            const branch = await git.currentBranch({ fs: this.fs, dir: this.dir, fullname: false }) || 'main';
            await git.merge({
                fs: this.fs,
                dir: this.dir,
                ours: branch,
                theirs,
                abortOnConflict: false,
                author: this.author
            });
            return [];
        } catch (e: unknown) {
            if (e instanceof Error && (e.name === 'MergeConflictError' || e.name === 'MergeNotSupportedError')) {
                const filepaths: string[] = (e as { data?: { filepaths?: string[] } }).data?.filepaths ?? [];

                if (filepaths.length === 0) {
                    throw new Error('Merge conflict detected but could not identify conflicting files. Please sync using a Git client.');
                }

                const today = new Date().toISOString().slice(0, 10);
                const conflictCopies: string[] = [];

                for (const filepath of filepaths) {
                    try {
                        const { blob } = await git.readBlob({ fs: this.fs, dir: this.dir, oid: theirs, filepath });

                        const dotIndex = filepath.lastIndexOf('.');
                        const base = dotIndex !== -1 ? filepath.slice(0, dotIndex) : filepath;
                        const ext = dotIndex !== -1 ? filepath.slice(dotIndex) : '';
                        const copyPath = `${base} (remote conflict - ${today})${ext}`;

                        await this.fs.promises.writeFile(copyPath, blob);
                        conflictCopies.push(copyPath);

                        await git.add({ fs: this.fs, dir: this.dir, filepath: copyPath });
                        await git.add({ fs: this.fs, dir: this.dir, filepath });
                    } catch (readErr) {
                        console.error(`[DirectGitSync] Failed to create conflict copy for "${filepath}":`, readErr);
                    }
                }

                return conflictCopies;
            }
            throw e;
        }
    }

    async push(url: string, token: string) {
        await git.push({
            fs: this.fs,
            http,
            dir: this.dir,
            remote: 'origin',
            onAuth: () => ({ username: token })
        });
    }
}
